global:

  app:
    metadata:
      tier: dbs
      capability: transactions
    pullPolicy: Always

  jwt:
    enabled: true
    existingSecret: "backbase-env-jwt"
    SIG_SECRET_KEY_fromSecret: true
    USERCTX_KEY_fromSecret: true

  registry:
    enabled: false

  activemq:
    enabled: true
    checkEnabled: true

  database:
    enabled: false

  env:
    BUILDINGBLOCKS_SECURITY_CSRF_ENABLED: "false"
    BACKBASE_PANDP_ENABLED: "false"

service:
  nameOverride: "transaction-manager"
app:
  image:
    repository: ados-transaction-manager
  resources:
    memory:
      ram: 1024