javaOpts:
  extra:
    - "-Djavax.net.ssl.trustStore=/opt/integration-sba/keystore-sba-prod.jks"
    - "-Djsse.enableSNIExtension=false"
volumes:
  - name: sba-jks-configmap
    configMap:
      name: sba-jks-configmap
volumeMounts:
  - name: sba-jks-configmap
    mountPath: /opt/integration-sba/keystore-sba-prod.jks
    subPath: keystore-sba-prod.jks
    readOnly: true

service:
  enabled: true

app:
  image:
    registry: default-route-openshift-image-registry.apps.cluster-apps-prd.ao.sbicdirectory.com/newsb24
    tag: 3.0.0-RC-SNAPSHOT