app:
  image:
    registry: default-route-openshift-image-registry.apps.cluster-apps-prd.ao.sbicdirectory.com/newsb24
    tag: 3.0.0-RC-SNAPSHOT
    pullPolicy: Always
  resources:
    memory:
      ram: 1024

# TODO: TBC after tech analysis
#database:
#  username: uat_cardsservice
#  existingSecret: backbase-env-database
#  existingSecretKey: cardsservice_key

javaOpts:
  extra:
    - "-Djavax.net.ssl.trustStore=/etc/ssl/java/certs/cacerts"
    - "-Djavax.net.ssl.trustStorePassword=changeit"

volumes:
  - name: sba-jks-configmap
    configMap:
      name: sba-jks-configmap
volumeMounts:
  - name: sba-jks-configmap
    mountPath: /etc/ssl/java/certs/cacerts
    subPath: cacerts
    readOnly: true

env:
  SBA_CORE_SCHEME: "https"
  SBA_CORE_HOST: "sba-api-in.ao.sbicdirectory.com/ados"
  SBA_CORE_IBMCLIENTID: "276ee69ac181f050b31614ae2f6d9ed4"
  SBA_CORE_CLIENTID:  "276ee69ac181f050b31614ae2f6d9ed4"
  SBA_CORE_CLIENTSECRET:  "e3da37aa1cce6f819a565a669c21ea52"
  SBA_CORE_APIBASEPATH: "cards"
  sba.core.route.customer: customer
  sba.core.route.cards: cards
  # Business function properties
  SBA_CARD_BUSINESSFUNCTION_RETAIL_LIMITS: "SBA MANAGE CARD LIMITS"
  SBA_CARD_BUSINESSFUNCTION_RETAIL_LOCK: "SBA CARD LOCK UNLOCK"
  SBA_CARD_BUSINESSFUNCTION_BUSINESS_LIMITS: "SBA BB MANAGE CARD LIMITS"
  SBA_CARD_BUSINESSFUNCTION_BUSINESS_LOCK: "SBA BB CARD LOCK UNLOCK"
  # Utility properties
  SBA_CARD_UTILITY_POSITION_LIMIT: 12