global:

  app:
    metadata:
      tier: dbs
      capability: currencies
    pullPolicy: Always

  jwt:
    enabled: true
    existingSecret: "backbase-env-jwt"
    SIG_SECRET_KEY_fromSecret: true
    USERCTX_KEY_fromSecret: true

  registry:
    enabled: false

  activemq:
    enabled: true
    checkEnabled: true

  database:
    enabled: true
    type: oracle

  env:
    BUILDINGBLOCKS_SECURITY_CSRF_ENABLED: "false"