app:
  image:
    registry: default-route-openshift-image-registry.apps.cluster-apps-prd.ao.sbicdirectory.com/newsb24
    tag: 3.0.0-RC-SNAPSHOT
env: #put in secrets
  IDENTITY_MASTERADMIN_USERNAME: "admin"
  IDENTITY_MASTERADMIN_REALMNAME: "master"
  IDENTITY_MASTERADMIN_CLIENTID: "admin-cli"
  "IDENTITY_REALMCONFIGURATION_REALMS_sbapb_ENABLEUSER": "true"
  "IDENTITY_REALMCONFIGURATION_REALMS_sbapb_USETEMPORARYPASSWORD": "true"
  "IDENTITY_REALMCONFIGURATION_FALLBACKOPTIONS_ENABLEUSER": "true"
  "IDENTITY_REALMCONFIGURATION_FALLBACKOPTIONS_USETEMPORARYPASSWORD": "true"
  "IDENTITY_READONLYATTRIBUTES": "modifyTimestamp,createTimestamp"
  "IDENTITY_DEFAULTROLES": "ROLE_group_user(USER)"
  "IDENTITY_DEFAULTGROUPS": "USER"
  "BACKBASE_IDENTITY_COMMUNICATION_HTTP_OBSERVATION_HIDEURIID": "false"
  "IDENTITY_REALMCONFIGURATION_REALMS_sbapb_REQUIRED_ACTION_1_IDENTITY": "custom-required-action-no-mapping"
  IDENTITY_SERVERURL: "http://identity-service:8080/auth"
