app:
  image:
    registry: default-route-openshift-image-registry.apps.cluster-apps-prd.ao.sbicdirectory.com/newsb24
    tag: 3.0.0-RC-SNAPSHOT
    pullPolicy: Always
  resources:
    memory:
      ram: 1024
    limits:
      memory:
        ram: 1024

database:
  username: user_pandp_service
  existingSecret: backbase-env-database
  existingSecretKey: userpandpservice_key

javaOpts:
  extra:
    - "-Djavax.net.ssl.trustStore=/etc/ssl/java/certs/cacerts"
    - "-Djavax.net.ssl.trustStorePassword=changeit"
volumes:
  - name: sba-jks-configmap
    configMap:
      name: sba-jks-configmap

volumeMounts:
  - name: sba-jks-configmap
    mountPath: /etc/ssl/java/certs/cacerts
    subPath: cacerts
    readOnly: true

ingress:
  enabled: false
  
env:
  # Spring properties
  SPRING_CONFIG_ADDITIONAL_LOCATION: "classpath:application-extension.yml"
  # BB properties
  BACKBASE_SECURITY_MTLS_ENABLED: "false"
  BACKBASE_SECURITY_PUBLIC_PATHS: "/integration-api/**"
  BACKBASE_USERS_IDENTITYENDPOINTSENABLED: "true"
  BACKBASE_USERS_IDENTITYINTEGRATIONENABLED: "true"
  BACKBASE_COMMUNICATION_SERVICES_USER_PROFILE_SCHEME: "http"
  BACKBASE_COMMUNICATION_SERVICES_USER_PROFILE_SERVICEID: "user-outbound"
  BACKBASE_APPROVALS_ENABLED: "true"
  backbase.users.sync-primary-to-identity-enabled: "true"
  # SBA properties
  SBA_CORE_SCHEME: "https"
  SBA_CORE_HOST: "sba-api-in.ao.sbicdirectory.com/ados"
  SBA_CORE_IBMCLIENTID: "276ee69ac181f050b31614ae2f6d9ed4"
  SBA_CORE_CLIENTID:  "276ee69ac181f050b31614ae2f6d9ed4"
  SBA_CORE_CLIENTSECRET:  "e3da37aa1cce6f819a565a669c21ea52"
  SBA_CORE_ROUTE_ARRANGEMENT: "arrangement"
  SBA_CORE_ROUTE_CUSTOMER: "customer"
  # STEP UP CONFIG FOR CHANGE PWD
  "backbase.security.rules-enabled": "true"
  "backbase.security.deny-all": "false"
  "backbase.security.rules.user-manager-client-api.step-up.acr-values": "step_up"
  "backbase.security.rules.user-manager-client-api.to.0.methods": "POST"
  "backbase.security.rules.user-manager-client-api.to.0.paths": "/client-api/v2/users/identities/password"
  "backbase.security.rules.user-manager-client-api.to.1.methods": "PUT"
  "backbase.security.rules.user-manager-client-api.to.1.paths": "/client-api/v2/users/identities/password/*"
  "backbase.security.rules.user-manager-client-api.to.2.methods": "DELETE"
  "backbase.security.rules.user-manager-client-api.to.2.paths": "/client-api/v2/users/identities/password/*"
  "backbase.security.rules.user-manager-client-api.when.match": "ALL"
  "backbase.security.rules.user-manager-client-api.when.values.0": "bb-su:change-pwd"
  "backbase.security.rules.user-manager-client-api.when.token": "CLIENT"
  "backbase.security.rules.user-manager-client-api.order": "1"