app:
  image:
    repository: ados-sms-connector
  resources:
    memory:
      ram: 1024

ingress:
  enabled: false
livenessProbe:
  enabled: true
  initialDelaySeconds: 150
readinessProbe:
  enabled: true
  initialDelaySeconds: 150

activemq:
  enabled: true

jwt:
  enabled: true
  SIG_SECRET_KEY_fromSecret: true
