# Default values come from backbase-app.

## Global values: Local values have precedence and mergeOverwrite globals
global:

  app:
    metadata:
      public: true
    # global.app.image configures the docker image to use.
    image:
      # app.image.registry is the docker repository tag for this deployment.
      registry: "default-route-openshift-image-registry.apps.cluster-apps-prd.ao.sbicdirectory.com/newsb24"
      # app.image.tag is the docker image tag for this deployment.
      tag: "2.355.0"
      pullPolicy: Always
    
  imagePullSecrets:
  - name: repo-backbase-com-image-pull-secrets
  - name: internal-registry-docker-config2
  env:
    #Temp routes
    API_ROOT: https://beta.sb24.standardbank.co.ao/api/
    AUTH_CLIENT_ID: sba-retail-web
    AUTH_REALM: sbapb
    AUTH_URL: https://beta.sb24identity.standardbank.co.ao/auth/

app:
  resources:
    cpu:
      minShares: 500
      maxShares: 800