service:
  nameOverride: "ingestion"

app:
  image:
    repository: ados-dbs-ingestion-service

jwt:
  enabled: true
  SIG_SECRET_KEY_fromSecret: true
  USERCTX_KEY_fromSecret: true

registry:
  enabled: false

activemq:
  enabled: true
  checkEnabled: true

ingress:
  enabled: false