global:
  app:
    image:
      registry: repo.backbase.com/backbase-docker-releases
      tag: 2022.01.6-LTS
    metadata:
      #For version 1.0.0 remove quotes for bool variable
      public: "'true'"