global:

  app:
    metadata:
      tier: dbs
      capability: access-control
    pullPolicy: Always

  jwt:
    enabled: true
    existingSecret: "backbase-env-jwt"
    SIG_SECRET_KEY_fromSecret: true
    USERCTX_KEY_fromSecret: true

  registry:
    enabled: false

  activemq:
    enabled: true
    checkEnabled: true

  database:
    enabled: false
    type: oracle

  env:
    BUILDINGBLOCKS_SECURITY_CSRF_ENABLED: "false"
    backbase.security.csrf.enabled: "false"
    "spring.liquibase.enabled": "true"
    "spring.datasource.validation-query": "SELECT 1 from dual"
    "spring.datasource.tomcat.validation-query": "SELECT 1 from dual"
    "spring.datasource.tomcat.max-active": "30"